'use strict';
const $ = id => document.getElementById(id);
const metrics = {systolic:['最高血圧','mmHg'],diastolic:['最低血圧','mmHg'],pulse:['脈拍','bpm'],weight:['体重','kg'],body_fat:['体脂肪率','%'],muscle:['骨格筋率','%'],visceral_fat:['内臓脂肪',''],bmi:['BMI',''],bmr:['基礎代謝','kcal'],body_age:['体年齢','歳']};
let users=[], devices=[], chartRecords=[], historyRecords=[], offset=0, activePage='overview', editedRecord=null, previousJobState='';
function element(tag, text, className) { const node=document.createElement(tag); if(text!==undefined) node.textContent=text; if(className) node.className=className; return node; }
function message(text, error=false) { $('message').textContent=text; $('message').className='message'+(error?' error':''); $('message').hidden=false; }
function localInput(value=new Date()) { const d=new Date(value); return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,19); }
function dateText(value) { return new Date(value).toLocaleString('ja-JP'); }
async function api(path, body, method='POST') { const options={cache:'no-store'}; if(body!==undefined) Object.assign(options,{method,headers:{'Content-Type':'application/json','X-SelfCare-Request':'1'},body:JSON.stringify(body)}); const response=await fetch(path,options); const data=await response.json(); if(!response.ok) throw new Error(data.error||'処理に失敗しました'); return data; }
function guarded(fn) { return async event=>{if(event)event.preventDefault(); const button=event?.currentTarget?.tagName==='BUTTON'?event.currentTarget:event?.currentTarget?.querySelector('button[type=submit]'); if(button)button.disabled=true; try {await fn(event);} catch(error){message(error.message,true);} finally {if(button)button.disabled=false;} }; }
function option(value, label) { const e=element('option',label); e.value=value; return e; }
function selectUsers(select, emptyLabel) {const old=select.value;select.replaceChildren();if(emptyLabel!==undefined)select.append(option('',emptyLabel));users.forEach(u=>select.append(option(u.id,u.name)));if([...select.options].some(o=>o.value===old))select.value=old;}
function currentUserName(id) {return users.find(u=>u.id===id)?.name||'不明';}
function filters(includeKind=false) { const p=new URLSearchParams(); if($('current-user').value)p.set('user_id',$('current-user').value); if($('since').value)p.set('since',new Date($('since').value+'T00:00:00').toISOString()); if($('until').value)p.set('until',new Date($('until').value+'T23:59:59').toISOString()); if(includeKind&&$('history-kind').value)p.set('kind',$('history-kind').value);return p; }
function showPage(id) {activePage=id;document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==id);document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$('page-name').textContent={overview:'ダッシュボード',records:'測定記録',devices:'機器と同期',settings:'設定・バックアップ'}[id];if(id==='settings')refreshDiagnostics().catch(e=>message(e.message,true));}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
async function refreshMeta() {const result=await Promise.all([api('/api/users'),api('/api/devices'),api('/api/status')]);[users,devices]=result;const status=result[2];$('version').textContent='Version '+status.version;selectUsers($('current-user'),'全員');document.querySelectorAll('.user-options').forEach(s=>selectUsers(s));selectUsers($('import-user'),'CSVに記録された利用者');if(users.length===1&&!$('current-user').value)$('current-user').value=users[0].id;renderUsers();renderDevices();renderBindings();}
function svgNode(tag, attrs, text) {const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [key,value] of Object.entries(attrs))n.setAttribute(key,String(value));if(text!==undefined)n.textContent=text;return n;}
function chart(target, series) {target.replaceChildren();if(!$('current-user').value){target.append(element('p','利用者を選択してください'));return;}const rows=[...chartRecords].reverse().filter(r=>series.some(s=>r.values[s.key]!==undefined));if(!rows.length){target.append(element('p','この期間の記録はありません'));return;}const width=500,height=230,pad={l:45,r:20,t:20,b:35};const values=rows.flatMap(r=>series.map(s=>r.values[s.key]).filter(v=>v!==undefined));const lo=Math.min(...values),hi=Math.max(...values),margin=Math.max((hi-lo)*.15,2);const ymin=Math.max(0,lo-margin),ymax=hi+margin;const times=rows.map(r=>new Date(r.measured_at).getTime());const tmin=Math.min(...times),tmax=Math.max(...times);const x=t=>pad.l+(tmax===tmin?.5:(t-tmin)/(tmax-tmin))*(width-pad.l-pad.r);const y=v=>height-pad.b-(v-ymin)/(ymax-ymin)*(height-pad.t-pad.b);const svg=svgNode('svg',{viewBox:`0 0 ${width} ${height}`,role:'img','aria-label':series.map(s=>metrics[s.key][0]).join('・')+'の推移'});for(let i=0;i<4;i++){const value=ymin+(ymax-ymin)*i/3;svg.append(svgNode('line',{x1:pad.l,x2:width-pad.r,y1:y(value),y2:y(value),stroke:'#e4ece7'}));svg.append(svgNode('text',{x:pad.l-9,y:y(value)+4,'text-anchor':'end',fill:'#80968b','font-size':11},value.toFixed(1)));}series.forEach(s=>{const points=rows.filter(r=>r.values[s.key]!==undefined);svg.append(svgNode('polyline',{points:points.map(r=>`${x(new Date(r.measured_at).getTime())},${y(r.values[s.key])}`).join(' '),fill:'none',stroke:s.color,'stroke-width':2}));points.forEach(r=>{const dot=svgNode('circle',{cx:x(new Date(r.measured_at).getTime()),cy:y(r.values[s.key]),r:3,fill:s.color});dot.append(svgNode('title',{},`${dateText(r.measured_at)} ${metrics[s.key][0]} ${r.values[s.key]} ${metrics[s.key][1]}`));svg.append(dot);});});[tmin,tmax].forEach((t,i)=>svg.append(svgNode('text',{x:i?width-pad.r:pad.l,y:height-8,'text-anchor':i?'end':'start',fill:'#80968b','font-size':11},new Date(t).toLocaleDateString('ja-JP',{month:'short',day:'numeric'}))));target.append(svg);}
async function refreshRecords() {const p=filters();p.set('limit','2000');const data=await api('/api/records?'+p);chartRecords=data.records;const bp=chartRecords.find(r=>r.kind==='blood_pressure'),weight=chartRecords.find(r=>r.kind==='body_composition');$('latest-bp').textContent=bp?`${bp.values.systolic} / ${bp.values.diastolic}`:'—';$('latest-weight').textContent=weight?weight.values.weight:'—';$('bp-date').textContent=bp?`${currentUserName(bp.user_id)}・${dateText(bp.measured_at)}`:'記録がありません';$('weight-date').textContent=weight?`${currentUserName(weight.user_id)}・${dateText(weight.measured_at)}`:'記録がありません';$('record-count').textContent=data.total.toLocaleString();$('record-period').textContent=($('since').value||'全期間')+' 〜 '+($('until').value||'現在');$('all-users-note').hidden=!!$('current-user').value;$('chart-limit').textContent=data.total>2000?'グラフは期間内の最新2,000件を表示しています。期間を絞ると細部を確認できます。':'';renderCharts();await refreshHistory();}
function renderCharts(){chart($('bp-chart'),[{key:'systolic',color:'#0b8c7c'},{key:'diastolic',color:'#e49a59'}]);chart($('weight-chart'),[{key:$('chart-metric').value,color:'#0b8c7c'}]);}
async function refreshHistory(){const p=filters(true);$('export').href='/api/export.csv?'+p;p.set('limit','100');p.set('offset',offset);const data=await api('/api/records?'+p);historyRecords=data.records;$('history-total').textContent=`${data.total}件・${data.total?offset+1:0}〜${offset+data.records.length}件`;$('previous').disabled=offset===0;$('next').disabled=offset+100>=data.total;const tbody=$('history');tbody.replaceChildren();if(!data.records.length){const td=element('td','記録がありません。「測定値を手入力」または機器の履歴同期から追加できます。');td.colSpan=5;const tr=element('tr');tr.append(td);tbody.append(tr);}data.records.forEach(r=>{const tr=element('tr');tr.append(element('td',dateText(r.measured_at)),element('td',currentUserName(r.user_id)));const values=element('td');Object.entries(r.values).forEach(([key,value])=>values.append(element('div',`${metrics[key][0]} ${value} ${metrics[key][1]}`)));const source=element('td',({manual:'手入力',bluetooth:'Bluetooth',csv:'CSV',api:'API',edited:'編集済み'})[r.source]||r.source);source.append(element('small',r.note));const actions=element('td');const edit=element('button','編集','secondary');edit.addEventListener('click',()=>editRecord(r));const remove=element('button','削除','danger');remove.addEventListener('click',guarded(async()=>{if(!confirm(`${dateText(r.measured_at)} の記録を削除しますか？`))return;await api('/api/records/'+r.id,{},'DELETE');message('記録を削除しました');await refreshRecords();}));actions.append(edit,remove);tr.append(values,source,actions);tbody.append(tr);});}
function resetRecord(){editedRecord=null;$('record-form').reset();$('record-form').elements.measured_at.value=localInput();if($('current-user').value)$('record-form').elements.user_id.value=$('current-user').value;recordKind();}
function recordKind(){const bp=$('record-kind').value==='blood_pressure';$('bp-fields').hidden=!bp;$('body-fields').hidden=bp;for(const key of Object.keys(metrics)){$('record-form').elements[key].required=bp?['systolic','diastolic','pulse'].includes(key):key==='weight';$('record-form').elements[key].disabled=bp?!['systolic','diastolic','pulse'].includes(key):['systolic','diastolic','pulse'].includes(key);}}
function editRecord(r){resetRecord();editedRecord=r;const f=$('record-form');f.elements.id.value=r.id;f.elements.user_id.value=r.user_id;f.elements.kind.value=r.kind;f.elements.measured_at.value=localInput(r.measured_at);f.elements.note.value=r.note;Object.entries(r.values).forEach(([k,v])=>f.elements[k].value=v);recordKind();$('manual-panel').open=true;$('manual-panel').scrollIntoView({behavior:'smooth'});}
$('record-kind').addEventListener('change',recordKind);$('cancel-edit').addEventListener('click',resetRecord);
$('record-form').addEventListener('submit',guarded(async()=>{const f=$('record-form'),form=new FormData(f),values={};for(const key of Object.keys(metrics)){if(form.get(key))values[key]=Number(form.get(key));}const body={user_id:form.get('user_id'),kind:form.get('kind'),measured_at:new Date(form.get('measured_at')).toISOString(),values,note:form.get('note')};if(editedRecord)Object.assign(body,{device_id:editedRecord.device_id,slot:editedRecord.slot});const result=await api('/api/records'+(editedRecord?'/'+editedRecord.id:''),body);message(editedRecord?'記録を更新しました':`${result.inserted}件保存しました（重複${result.duplicates}件）`);resetRecord();await refreshRecords();}));
function renderUsers(){$('user-list').replaceChildren();users.forEach(u=>{const row=element('div',undefined,'user-row');row.append(element('strong',u.name),element('small','ID: '+u.id));const edit=element('button','名前を変更','secondary');edit.addEventListener('click',guarded(async()=>{const name=prompt('利用者名',u.name);if(name===null)return;await api('/api/users',{id:u.id,name});await refreshMeta();await refreshRecords();}));const del=element('button','削除','danger');del.addEventListener('click',guarded(async()=>{if(!confirm(u.name+' を削除しますか？'))return;await api('/api/users/'+u.id,{},'DELETE');await refreshMeta();}));row.append(edit,del);$('user-list').append(row);});}
$('user-form').addEventListener('submit',guarded(async()=>{const f=$('user-form');const user=await api('/api/users',{name:f.elements.name.value});f.reset();await refreshMeta();$('current-user').value=user.id;resetRecord();await refreshRecords();message('利用者を追加しました');}));
function renderBindings(saved){const values=saved||Object.fromEntries([...$('bindings').querySelectorAll('select')].map(s=>[s.name,s.value]));$('bindings').replaceChildren();const count=$('device-model').value==='HEM-6232T'?2:4;for(let i=1;i<=count;i++){const label=element('label','利用者番号 '+i),select=element('select');select.name=String(i);selectUsers(select,'同期しない');select.value=values[String(i)]||'';label.append(select);$('bindings').append(label);}}
function resetDevice(){$('device-form').reset();$('device-form').elements.id.value='';renderBindings({});}
$('device-model').addEventListener('change',()=>renderBindings());$('reset-device').addEventListener('click',resetDevice);
function editDevice(d){const f=$('device-form');for(const key of ['id','name','model','address','adapter','interval','utc_offset_minutes','transport'])f.elements[key].value=d[key];f.elements.auto_sync.checked=d.auto_sync;f.elements.exclusive.checked=d.exclusive;renderBindings(d.bindings);$('device-panel').open=true;$('device-panel').scrollIntoView({behavior:'smooth'});}
function renderDevices(){$('device-list').replaceChildren();devices.forEach(d=>{const card=element('article',undefined,'card'),header=element('div',undefined,'row');header.append(element('h2',d.name),element('span',d.paired?'ペアリング済み':'未ペアリング','badge'));card.append(header,element('p',`${d.model}・${d.address||'アドレス未設定'}・${d.adapter}`),element('p',`自動同期: ${d.auto_sync?'ON / '+d.interval+'秒':'OFF'}　利用者割当: ${Object.entries(d.bindings).map(([s,u])=>s+'番 '+currentUserName(u)).join(' / ')||'未設定'}`));const row=element('div',undefined,'row');for(const [action,label] of [['pair','ペアリング'],['sync','履歴を同期']]){const b=element('button',label,action==='pair'?'secondary':'');b.addEventListener('click',guarded(async()=>{if(action==='pair'&&!confirm('機器をペアリングモードにしてください。既存のスマートフォン連携キーを変更する場合があります。続けますか？'))return;await api('/api/jobs',{action,device_id:d.id});message('処理を受け付けました。操作履歴で進捗を確認できます');await refreshJobs();}));row.append(b);}const edit=element('button','設定','secondary');edit.addEventListener('click',()=>editDevice(d));const remove=element('button','削除','danger');remove.addEventListener('click',guarded(async()=>{if(!confirm('この機器登録を削除しますか？'))return;await api('/api/devices/'+d.id,{},'DELETE');await refreshMeta();}));row.append(edit,remove);card.append(row);$('device-list').append(card);});}
$('device-form').addEventListener('submit',guarded(async()=>{const f=$('device-form'),form=new FormData(f),body=Object.fromEntries(form);body.auto_sync=f.elements.auto_sync.checked;body.exclusive=f.elements.exclusive.checked;body.interval=Number(form.get('interval'));body.utc_offset_minutes=Number(form.get('utc_offset_minutes'));body.bindings=Object.fromEntries([...$('bindings').querySelectorAll('select')].filter(s=>s.value).map(s=>[s.name,s.value]));await api('/api/devices',body);resetDevice();await refreshMeta();message('機器設定を保存しました');}));
$('scan').addEventListener('click',guarded(async()=>{await api('/api/jobs',{action:'scan',adapter:$('scan-adapter').value,exclusive:$('scan-exclusive').checked,transport:$('scan-transport').value});message('スキャンを開始しました');await refreshJobs();}));
async function refreshJobs(){const jobs=await api('/api/jobs');$('jobs').replaceChildren();if(!jobs.length)$('jobs').append(element('p','まだ同期・操作履歴はありません'));jobs.forEach(j=>{const row=element('div',undefined,'job '+j.state);row.append(element('strong',({queued:'待機中',running:'実行中',done:'完了',failed:'失敗'})[j.state]),element('span',`${({scan:'スキャン',pair:'ペアリング',sync:'同期'})[j.action]} — ${devices.find(d=>d.id===j.device_id)?.name||'Bluetooth'}`),element('small',`${dateText(j.created_at)}　${j.message}`));$('jobs').append(row);});const scan=jobs.find(j=>j.action==='scan'&&j.state==='done'&&j.result);if(scan){const result=JSON.parse(scan.result);$('scan-results').replaceChildren();result.devices.forEach(d=>{const row=element('div',undefined,'scan-result');row.append(element('span',`${d.name}　${d.address}　${d.rssi} dBm`));const use=element('button','登録に使う','secondary');use.addEventListener('click',()=>{resetDevice();const f=$('device-form');f.elements.address.value=d.address;f.elements.name.value=d.name;f.elements.adapter.value=$('scan-adapter').value;f.elements.exclusive.checked=$('scan-exclusive').checked;f.elements.transport.value=$('scan-transport').value;const n=d.name.toLowerCase();if(n.includes('hbf-228')||n.startsWith('blesmart_0001000b'))f.elements.model.value='HBF-228T';renderBindings();$('device-panel').open=true;$('device-panel').scrollIntoView({behavior:'smooth'});});row.append(use);$('scan-results').append(row);});}const state=jobs.map(j=>j.id+':'+j.state).join();if(previousJobState&&state!==previousJobState&&jobs.some(j=>j.state==='done')){await refreshMeta();await refreshRecords();}previousJobState=state;}
async function refreshDiagnostics(){const [d,s]=await Promise.all([api('/api/diagnostics'),api('/api/status')]);const rows={'バージョン':s.version,'CPU':s.architecture||'不明','USB Bluetooth':s.bluetooth_adapters.join(', ')||'未検出','Bluetooth実行環境':d.mode==='homehub'?'共通Bluetoothサービス':d.mode==='container'?'Container Station（専用）':'NASネイティブ','Python BLE':d.bleak?'導入済み':'未導入','D-Bus':d.dbus?'検出':'未検出','収集ワーカー':d.worker_alive?'稼働中':'停止','保存先':d.data_path};if(d.bridge_error)rows['ブリッジエラー']=d.bridge_error;$('diagnostics').replaceChildren();Object.entries(rows).forEach(([k,v])=>$('diagnostics').append(element('dt',k),element('dd',v)));}
$('refresh-diagnostics').addEventListener('click',guarded(refreshDiagnostics));
$('import-form').addEventListener('submit',guarded(async()=>{const f=$('import-form'),file=f.elements.file.files[0];if(file.size>8*1024*1024)throw Error('CSVは8MB以内です');const result=await api('/api/import',{csv:await file.text(),user_id:f.elements.user_id.value||null});message(`${result.inserted}件取り込みました（重複${result.duplicates}件）`);await refreshRecords();}));
$('restore-form').addEventListener('submit',guarded(async()=>{const file=$('restore-form').elements.file.files[0];if(file.size>32*1024*1024)throw Error('バックアップは32MB以内です');if(!confirm('空の保存先にバックアップを復元します。続けますか？'))return;const result=await api('/api/restore',JSON.parse(await file.text()));await refreshMeta();await refreshRecords();message(`${result.restored}件復元しました。Bluetoothは再ペアリングしてください`);}));
$('check-update').addEventListener('click',guarded(async()=>{$('update-message').textContent='更新を確認中…';const d=await api('/api/update');$('update-message').replaceChildren();if(d.available){const a=element('a',`${d.version} QPKGをダウンロード`);a.href=d.url;a.rel='noopener noreferrer';$('update-message').append(a);}else $('update-message').textContent='現在のバージョンが最新です';}));
$('apply-filter').addEventListener('click',guarded(async()=>{if($('since').value&&$('until').value&&$('since').value>$('until').value)throw Error('開始日を終了日以前にしてください');offset=0;await refreshRecords();}));
$('current-user').addEventListener('change',guarded(async()=>{offset=0;resetRecord();await refreshRecords();}));$('history-kind').addEventListener('change',guarded(async()=>{offset=0;await refreshHistory();}));$('chart-metric').addEventListener('change',renderCharts);$('previous').addEventListener('click',guarded(async()=>{offset=Math.max(0,offset-100);await refreshHistory();}));$('next').addEventListener('click',guarded(async()=>{offset+=100;await refreshHistory();}));
(async()=>{try{await refreshMeta();resetRecord();await refreshRecords();await refreshJobs();if(!users.length){showPage('settings');message('最初に利用者を追加してください。その後、手入力や機器の登録ができます。');}setInterval(()=>{if(!document.hidden)refreshJobs().catch(()=>{});},5000);}catch(error){message('読み込みに失敗しました: '+error.message,true);}})();
