'use strict';
const $ = id => document.getElementById(id);
const metrics = {systolic:['最高血圧','mmHg'],diastolic:['最低血圧','mmHg'],pulse:['脈拍','bpm'],weight:['体重','kg'],body_fat:['体脂肪率','%'],muscle:['骨格筋率','%'],visceral_fat:['内臓脂肪',''],bmi:['BMI',''],bmr:['基礎代謝','kcal'],body_age:['体年齢','歳']};
let users=[], devices=[], chartRecords=[], historyRecords=[], offset=0, activePage='overview', editedRecord=null, previousJobState='', previousScanRender='', wellnessProfile=null, wellnessProfileUser=null;
function element(tag, text, className) { const node=document.createElement(tag); if(text!==undefined) node.textContent=text; if(className) node.className=className; return node; }
function message(text, error=false) { const close=element('button',undefined,'message-close');close.type='button';close.setAttribute('aria-label','通知を閉じる');close.addEventListener('click',()=>{$('message').hidden=true;});$('message').replaceChildren(element('span',text),close); $('message').className='message'+(error?' error':''); $('message').hidden=false; }
function localInput(value=new Date()) { const d=new Date(value); return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,19); }
function dateText(value) { return new Date(value).toLocaleString('ja-JP'); }
const tokyoDay=new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'});
function markMeasuredToday(id,record,now=new Date()){$(id).hidden=!record||tokyoDay.format(new Date(record.measured_at))!==tokyoDay.format(now);}
async function api(path, body, method='POST') { const options={cache:'no-store'}; if(body!==undefined) Object.assign(options,{method,headers:{'Content-Type':'application/json','X-SelfCare-Request':'1'},body:JSON.stringify(body)}); const response=await fetch(path,options); const data=await response.json(); if(!response.ok) throw new Error(data.error||'処理に失敗しました'); return data; }
function guarded(fn) { return async event=>{if(event)event.preventDefault(); const button=event?.currentTarget?.tagName==='BUTTON'?event.currentTarget:event?.currentTarget?.querySelector('button[type=submit]'); if(button)button.disabled=true; try {await fn(event);} catch(error){message(error.message,true);} finally {if(button)button.disabled=false;} }; }
function option(value, label) { const e=element('option',label); e.value=value; return e; }
function selectUsers(select, emptyLabel) {const old=select.value;select.replaceChildren();if(emptyLabel!==undefined)select.append(option('',emptyLabel));users.forEach(u=>select.append(option(u.id,u.name)));if([...select.options].some(o=>o.value===old))select.value=old;}
function currentUserName(id) {return users.find(u=>u.id===id)?.name||'不明';}
function filters(includeKind=false) { const p=new URLSearchParams(); if($('current-user').value)p.set('user_id',$('current-user').value); if($('since').value)p.set('since',new Date($('since').value+'T00:00:00').toISOString()); if($('until').value)p.set('until',new Date($('until').value+'T23:59:59').toISOString()); if(includeKind&&$('history-kind').value)p.set('kind',$('history-kind').value);return p; }
function showPage(id) {if(activePage!==id)$('message').hidden=true;activePage=id;document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==id);document.querySelectorAll('[data-page]').forEach(b=>{const active=b.dataset.page===id;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});$('page-name').textContent={overview:'ダッシュボード',records:'測定記録',wellness:'健康サポート',devices:'機器と同期',settings:'設定・バックアップ'}[id];if(id==='settings')refreshDiagnostics().catch(e=>message(e.message,true));if(id==='wellness')refreshWellness().catch(e=>message(e.message,true));}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
async function refreshMeta() {const result=await Promise.all([api('/api/users'),api('/api/devices'),api('/api/status')]);[users,devices]=result;const status=result[2];$('version').textContent='Version '+status.version;selectUsers($('current-user'),'全員');document.querySelectorAll('.user-options').forEach(s=>selectUsers(s));selectUsers($('import-user'),'CSVに記録された利用者');selectUsers($('omron-user'),'利用者を選択');if(users.length===1){if(!$('current-user').value)$('current-user').value=users[0].id;if(!$('omron-user').value)$('omron-user').value=users[0].id;}renderUsers();renderDevices();renderBindings();}
function svgNode(tag, attrs, text) {const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [key,value] of Object.entries(attrs))n.setAttribute(key,String(value));if(text!==undefined)n.textContent=text;return n;}
function chart(target, series, limits=[]) {target.replaceChildren();if(!$('current-user').value){target.append(element('p','利用者を選択してください'));return;}const rows=[...chartRecords].reverse().filter(r=>series.some(s=>r.values[s.key]!==undefined));if(!rows.length){target.append(element('p','この期間の記録はありません'));return;}const width=500,height=230,pad={l:45,r:20,t:20,b:35};const values=rows.flatMap(r=>series.map(s=>r.values[s.key]).filter(v=>v!==undefined));const lo=Math.min(...values,...limits.map(l=>l.value)),hi=Math.max(...values,...limits.map(l=>l.value)),margin=Math.max((hi-lo)*.15,2);const ymin=Math.max(0,lo-margin),ymax=hi+margin;const times=rows.map(r=>new Date(r.measured_at).getTime());const tmin=Math.min(...times),tmax=Math.max(...times);const x=t=>pad.l+(tmax===tmin?.5:(t-tmin)/(tmax-tmin))*(width-pad.l-pad.r);const y=v=>height-pad.b-(v-ymin)/(ymax-ymin)*(height-pad.t-pad.b);const svg=svgNode('svg',{viewBox:`0 0 ${width} ${height}`,role:'img','aria-label':series.map(s=>metrics[s.key][0]).join('・')+'の推移'});for(let i=0;i<4;i++){const value=ymin+(ymax-ymin)*i/3;svg.append(svgNode('line',{x1:pad.l,x2:width-pad.r,y1:y(value),y2:y(value),stroke:'var(--chart-grid)'}));svg.append(svgNode('text',{x:pad.l-9,y:y(value)+4,'text-anchor':'end',fill:'var(--chart-label)','font-size':11},value.toFixed(1)));}limits.forEach(l=>{svg.append(svgNode('line',{x1:pad.l,x2:width-pad.r,y1:y(l.value),y2:y(l.value),stroke:l.color||'var(--chart-limit)','stroke-width':1,'stroke-dasharray':'5 4'}));svg.append(svgNode('text',{x:width-pad.r-3,y:y(l.value)-3,'text-anchor':'end',fill:l.color||'var(--chart-limit)','font-size':10},l.label));});series.forEach(s=>{const points=rows.filter(r=>r.values[s.key]!==undefined);svg.append(svgNode('polyline',{points:points.map(r=>`${x(new Date(r.measured_at).getTime())},${y(r.values[s.key])}`).join(' '),fill:'none',stroke:s.color,'stroke-width':2}));points.forEach(r=>{const dot=svgNode('circle',{cx:x(new Date(r.measured_at).getTime()),cy:y(r.values[s.key]),r:3,fill:s.color});dot.append(svgNode('title',{},`${dateText(r.measured_at)} ${metrics[s.key][0]} ${r.values[s.key]} ${metrics[s.key][1]}`));svg.append(dot);});});[tmin,tmax].forEach((t,i)=>svg.append(svgNode('text',{x:i?width-pad.r:pad.l,y:height-8,'text-anchor':i?'end':'start',fill:'var(--chart-label)','font-size':11},new Date(t).toLocaleDateString('ja-JP',{month:'short',day:'numeric'}))));target.append(svg);}
async function refreshRecords() {const p=filters();p.set('limit','2000');const data=await api('/api/records?'+p);chartRecords=data.records;const bp=chartRecords.find(r=>r.kind==='blood_pressure'),weight=chartRecords.find(r=>r.kind==='body_composition');$('latest-bp').textContent=bp?`${bp.values.systolic} / ${bp.values.diastolic}`:'—';$('latest-weight').textContent=weight?weight.values.weight:'—';$('bp-date').textContent=bp?`${currentUserName(bp.user_id)}・${dateText(bp.measured_at)}`:'記録がありません';$('weight-date').textContent=weight?`${currentUserName(weight.user_id)}・${dateText(weight.measured_at)}`:'記録がありません';markMeasuredToday('bp-today-star',bp);markMeasuredToday('weight-today-star',weight);renderBmi();$('all-users-note').hidden=!!$('current-user').value;$('chart-limit').textContent=data.total>2000?'グラフは期間内の最新2,000件を表示しています。期間を絞ると細部を確認できます。':'';renderCharts();await refreshHistory();if($('current-user').value)await refreshWellness();else{wellnessProfile=null;renderCharts();}}
function renderBmi(){
 const userId=$('current-user').value;
 const weight=chartRecords.find(r=>r.kind==='body_composition'&&(!userId||r.user_id===userId));
 const measured=weight?.values.bmi;
 const height=userId&&wellnessProfileUser===userId?wellnessProfile?.height_cm:null;
 const calculated=weight&&height&&Number.isFinite(weight.values.weight)?weight.values.weight/(height/100)**2:null;
 const value=Number.isFinite(measured)?measured:calculated;
 $('latest-bmi').textContent=Number.isFinite(value)?value.toFixed(1):'—';
 $('bmi-date').textContent=Number.isFinite(value)?`${currentUserName(weight.user_id)}・${dateText(weight.measured_at)}${Number.isFinite(measured)?'':'（身長から算出）'}`:weight?'健康サポートで身長を設定してください':'記録がありません';
}
function renderCharts(){const p=wellnessProfile;const bp=p?[['bp_sys_low','最高 下限'],['bp_sys_high','最高 上限'],['bp_dia_low','最低 下限'],['bp_dia_high','最低 上限']].map(([key,label])=>({value:p[key],label})):[];chart($('bp-chart'),[{key:'systolic',color:'var(--chart-primary)'},{key:'diastolic',color:'var(--chart-secondary)'}],bp);chart($('weight-chart'),[{key:$('chart-metric').value,color:'var(--chart-primary)'}],p&&$('chart-metric').value==='bmi'?[{value:p.bmi_low,label:'BMI 下限'},{value:p.bmi_high,label:'BMI 上限'}]:[]);}
async function refreshHistory(){const p=filters(true);$('export').href='/api/export.csv?'+p;p.set('limit','100');p.set('offset',offset);const data=await api('/api/records?'+p);historyRecords=data.records;$('history-total').textContent=`${data.total}件・${data.total?offset+1:0}〜${offset+data.records.length}件`;$('previous').disabled=offset===0;$('next').disabled=offset+100>=data.total;const tbody=$('history');tbody.replaceChildren();if(!data.records.length){const td=element('td','記録がありません。「測定値を手入力」または機器の履歴同期から追加できます。');td.colSpan=5;const tr=element('tr');tr.append(td);tbody.append(tr);}data.records.forEach(r=>{const tr=element('tr');tr.append(element('td',dateText(r.measured_at)),element('td',currentUserName(r.user_id)));const values=element('td',undefined,'record-values');const more=element('details',undefined,'record-more');more.append(element('summary','体組成の詳細'));for(const [key,value] of Object.entries(r.values)){const entry=element('div',`${metrics[key][0]} ${value} ${metrics[key][1]}`);(['weight','body_fat','bmi','systolic','diastolic','pulse'].includes(key)?values:more).append(entry);}if(more.children.length>1)values.append(more);const source=element('td',({manual:'手入力',bluetooth:'Bluetooth',csv:'CSV',api:'API',edited:'編集済み'})[r.source]||r.source);source.append(element('small',r.note));const actions=element('td');const edit=element('button','編集','secondary');edit.addEventListener('click',()=>editRecord(r));const remove=element('button','削除','danger');remove.addEventListener('click',guarded(async()=>{if(!confirm(`${dateText(r.measured_at)} の記録を削除しますか？`))return;await api('/api/records/'+r.id,{},'DELETE');message('記録を削除しました');await refreshRecords();}));const controls=element('details',undefined,'record-controls');controls.append(element('summary','編集・削除'));const buttons=element('div',undefined,'row');buttons.append(edit,remove);controls.append(buttons);actions.append(controls);tr.append(values,source,actions);['測定日時','利用者','測定値','取込元・メモ','操作'].forEach((label,i)=>tr.children[i].dataset.label=label);tbody.append(tr);});}
function resetRecord(){editedRecord=null;$('record-form').reset();$('record-form').elements.measured_at.value=localInput();if($('current-user').value)$('record-form').elements.user_id.value=$('current-user').value;recordKind();}
function recordKind(){const bp=$('record-kind').value==='blood_pressure';$('bp-fields').hidden=!bp;$('body-fields').hidden=bp;for(const key of Object.keys(metrics)){$('record-form').elements[key].required=bp?['systolic','diastolic','pulse'].includes(key):key==='weight';$('record-form').elements[key].disabled=bp?!['systolic','diastolic','pulse'].includes(key):['systolic','diastolic','pulse'].includes(key);}}
function editRecord(r){resetRecord();editedRecord=r;const f=$('record-form');f.elements.id.value=r.id;f.elements.user_id.value=r.user_id;f.elements.kind.value=r.kind;f.elements.measured_at.value=localInput(r.measured_at);f.elements.note.value=r.note;Object.entries(r.values).forEach(([k,v])=>f.elements[k].value=v);recordKind();$('manual-panel').open=true;$('manual-panel').scrollIntoView({behavior:'smooth'});}
$('record-kind').addEventListener('change',recordKind);$('cancel-edit').addEventListener('click',resetRecord);
$('record-form').addEventListener('submit',guarded(async()=>{const f=$('record-form'),form=new FormData(f),values={};for(const key of Object.keys(metrics)){if(form.get(key))values[key]=Number(form.get(key));}const body={user_id:form.get('user_id'),kind:form.get('kind'),measured_at:new Date(form.get('measured_at')).toISOString(),values,note:form.get('note')};if(editedRecord)Object.assign(body,{device_id:editedRecord.device_id,slot:editedRecord.slot});const result=await api('/api/records'+(editedRecord?'/'+editedRecord.id:''),body);message(editedRecord?'記録を更新しました':`${result.inserted}件保存しました（重複${result.duplicates}件）`);resetRecord();await refreshRecords();}));
function renderUsers(){$('user-list').replaceChildren();users.forEach(u=>{const row=element('div',undefined,'user-row');row.append(element('strong',u.name),element('small','ID: '+u.id));const edit=element('button','名前を変更','secondary');edit.addEventListener('click',guarded(async()=>{const name=prompt('利用者名',u.name);if(name===null)return;await api('/api/users',{id:u.id,name});await refreshMeta();await refreshRecords();}));const del=element('button','削除','danger');del.addEventListener('click',guarded(async()=>{if(!confirm(u.name+' を削除しますか？'))return;await api('/api/users/'+u.id,{},'DELETE');await refreshMeta();}));row.append(edit,del);$('user-list').append(row);});}
$('user-form').addEventListener('submit',guarded(async()=>{const f=$('user-form');const user=await api('/api/users',{name:f.elements.name.value});f.reset();await refreshMeta();$('current-user').value=user.id;resetRecord();await refreshRecords();message('利用者を追加しました');}));
function renderBindings(saved){const values=saved||Object.fromEntries([...$('bindings').querySelectorAll('select')].map(s=>[s.name,s.value]));$('bindings').replaceChildren();const count=$('device-model').value==='HEM-6232T'?2:4;for(let i=1;i<=count;i++){const label=element('label','利用者番号 '+i),select=element('select');select.name=String(i);selectUsers(select,'同期しない');select.value=values[String(i)]||'';label.append(select);$('bindings').append(label);}}
function syncModeOptions(){const f=$('device-form'),direct=f.elements.transport.value==='direct';f.elements.sync_mode.options[0].disabled=direct;if(direct)f.elements.sync_mode.value='interval';}
$('device-form').elements.transport.addEventListener('change',syncModeOptions);
function resetDevice(){$('device-form').reset();syncModeOptions();$('device-form').elements.id.value='';renderBindings({});}
$('device-model').addEventListener('change',()=>renderBindings());$('reset-device').addEventListener('click',resetDevice);
function editDevice(d){const f=$('device-form');for(const key of ['id','name','model','address','adapter','interval','utc_offset_minutes','transport','sync_mode'])f.elements[key].value=d[key];syncModeOptions();f.elements.auto_sync.checked=d.auto_sync;f.elements.exclusive.checked=d.exclusive;renderBindings(d.bindings);$('device-panel').open=true;$('device-panel').scrollIntoView({behavior:'smooth'});}
function renderDevices(){$('device-list').replaceChildren();devices.forEach(d=>{const card=element('article',undefined,'card device-card'),header=element('div',undefined,'device-header');header.append(element('h2',d.name),element('span',d.paired?'ペアリング済み':'未ペアリング','badge'));card.append(header);const info=element('dl',undefined,'device-info');for(const [label,value] of [['機種',d.model],['接続',`${d.address||'アドレス未設定'} / ${d.adapter}`],['自動同期',d.auto_sync?(d.sync_mode==='listen'?`待ち受け・1日1回${d.automatic_synced_today?'（本日完了）':''}`:`周期検索・1日1回${d.automatic_synced_today?'（本日完了）':''}`):'OFF'],['利用者',Object.entries(d.bindings).map(([s,u])=>s+'番 '+currentUserName(u)).join(' / ')||'未設定']]){info.append(element('dt',label),element('dd',value));}card.append(info);const row=element('div',undefined,'device-actions'),extra=element('details',undefined,'device-extra'),secondary=element('div',undefined,'device-actions');extra.append(element('summary','その他の操作・診断'),secondary);for(const [action,label] of [['pair','ペアリング'],['diagnose_pair','診断付きペアリング'],['sync','履歴を同期'],['diagnose','診断付き同期']]){const b=element('button',label,action==='sync'?'':'secondary');b.addEventListener('click',guarded(async()=>{if(action==='pair'&&!confirm('機器をペアリングモードにしてください。既存のスマートフォン連携キーを変更する場合があります。続けますか？'))return;if(action==='diagnose_pair'&&!confirm((d.model==='HBF-228T'?'体組成計のBluetoothボタンを長押ししてペアリングモードにしてください。':'血圧計を -P- 表示にしてください。')+'診断結果を保存します。ペアリングに成功するとスマホとの接続キーが変わる場合があります。開始しますか？'))return;if(action==='diagnose'&&!confirm('測定値や一部の生データを診断結果としてNAS内の操作履歴に記録します。同期を開始しますか？'))return;await api('/api/jobs',{action:action==='diagnose'?'sync':action==='diagnose_pair'?'pair':action,device_id:d.id,...(action.startsWith('diagnose')?{diagnostic:true}:{})});message('処理を受け付けました。操作履歴で進捗を確認できます');await refreshJobs();}));(action==='sync'?row:secondary).append(b);}const edit=element('button','設定','secondary');edit.addEventListener('click',()=>editDevice(d));const remove=element('button','削除','danger');remove.addEventListener('click',guarded(async()=>{if(!confirm('機器登録とNAS側のペアリングキーを削除します。保存済みの測定記録は残ります。削除しますか？'))return;await api('/api/devices/'+d.id,{},'DELETE');await refreshMeta();message('機器登録を削除しました。測定記録は保持しています');}));row.append(edit);secondary.append(remove);card.append(row,extra);if(d.model==='HBF-228T'){const help=element('details',undefined,'device-extra');help.append(element('summary','体組成計のデータ転送方法'),element('p','本体のBluetoothタッチボタンを短く触れ、すぐに「履歴を同期」を押してください。長押しはペアリング用です。検出できない場合はNASへ近づけ、スマートフォンのBluetoothを一時的にオフにして「診断付き同期」を試してください。'));card.append(help);}$('device-list').append(card);});}
$('device-form').addEventListener('submit',guarded(async()=>{const f=$('device-form'),form=new FormData(f),body=Object.fromEntries(form);body.auto_sync=f.elements.auto_sync.checked;body.exclusive=f.elements.exclusive.checked;body.interval=Number(form.get('interval'));body.utc_offset_minutes=Number(form.get('utc_offset_minutes'));body.bindings=Object.fromEntries([...$('bindings').querySelectorAll('select')].filter(s=>s.value).map(s=>[s.name,s.value]));await api('/api/devices',body);resetDevice();await refreshMeta();message('機器設定を保存しました');}));
$('scan').addEventListener('click',guarded(async()=>{await api('/api/jobs',{action:'scan',adapter:$('scan-adapter').value,exclusive:$('scan-exclusive').checked,transport:$('scan-transport').value});message('スキャンを開始しました');await refreshJobs();}));
function detectedModel(name){const n=(name||'').toLowerCase();if(/(?:^|[^a-z0-9])hem-6232t(?:$|[^a-z0-9])/.test(n))return 'HEM-6232T';if(/(?:^|[^a-z0-9])hbf-228t(?:$|[^a-z0-9])/.test(n)||/^blesmart_0001000b[0-9a-f]*$/.test(n))return 'HBF-228T';return '';}
function renderScan(scan){
 const target=$('scan-results');target.replaceChildren();
 if(!scan||scan.state!=='done'||!scan.result)return;
 if(Date.now()-Date.parse(scan.created_at)>180000){target.append(element('p','検出結果が古くなりました。機器を通信可能にして再スキャンしてください。'));return;}
 const result=JSON.parse(scan.result);
 if(!result.adapter||!result.transport){target.append(element('p','更新前の検出結果です。機器を再スキャンしてください。'));return;}
 if(!result.devices.length){target.append(element('p','機器が見つかりません。機器をペアリングモードにして再スキャンしてください。'));return;}
 for(const d of result.devices){
  const row=element('div',undefined,'scan-result'),controls=element('div',undefined,'scan-controls');
  row.append(element('span',`${d.name}　${d.address}　${d.rssi} dBm`));
  const existing=devices.find(device=>device.address.toUpperCase()===d.address.toUpperCase());
  if(existing){row.append(element('span','登録済み: '+existing.name,'badge'));target.append(row);continue;}
  const model=element('select');model.setAttribute('aria-label',d.name+' の機種');model.append(option('','機種を選択'),option('HEM-6232T','血圧計 HEM-6232T'),option('HBF-228T','体組成計 HBF-228T'));model.value=detectedModel(d.name);
  const user=element('select');user.setAttribute('aria-label','測定する利用者');selectUsers(user,'利用者を選択');if(users.length===1)user.value=users[0].id;
  const slot=element('select');slot.setAttribute('aria-label','機器の利用者番号');
  function fillSlots(){slot.replaceChildren();for(let number=1;number<=(model.value==='HBF-228T'?4:2);number++)slot.append(option(String(number),'機器の'+number+'番'));}
  model.addEventListener('change',fillSlots);fillSlots();
  const use=element('button','登録してペアリング','secondary');
  use.addEventListener('click',guarded(async()=>{
   if(!users.length)throw Error('先に利用者を追加してください');
   if(!model.value)throw Error('機種を選択してください。名前からは特定できません');
   if(!user.value)throw Error('測定する利用者を選択してください');
   if(!confirm('機器をペアリングモードにしてください。既存のスマートフォン連携キーが変更される場合があります。続けますか？'))return;
   const transport=result.transport;
   const saved=await api('/api/devices',{name:model.value,model:model.value,address:d.address,
    adapter:result.adapter,transport,exclusive:transport==='direct',
    bindings:{[slot.value]:user.value},auto_sync:true,sync_mode:transport==='homehub'?'listen':'interval',interval:300,
    utc_offset_minutes:-new Date().getTimezoneOffset()});
   await refreshMeta();
   try{await api('/api/jobs',{action:'pair',device_id:saved.id});}
   catch(error){throw Error('機器は登録されました。ペアリング開始に失敗したため、機器一覧の「ペアリング」から再試行してください: '+error.message);}
   message('登録してペアリングを開始しました。操作履歴で完了を確認してください');
   await refreshJobs();
  }));
  controls.append(model,user,slot,use);row.append(controls);target.append(row);
 }
}
async function refreshJobs(){if(activePage==='devices'){try{const status=await api('/api/listener');$('listen-status').textContent=status.error|| (status.configured?(status.busy?'待ち受け：通信処理中（完了後に再開）':status.ready?'待ち受け：機器からの通信を検知しています':'待ち受け：準備中'):'待ち受け：有効な対象機器なし');if(status.waiting?.length)$('listen-status').textContent+=' ／ '+status.waiting.map(w=>`${devices.find(d=>d.id===w.device_id)?.name||'機器'}：${w.attempt===2?'再試行':'同期'}まで約${w.seconds}秒`).join('・');if(status.completed_today?.length)$('listen-status').textContent+=' ／ 本日の自動同期済み：'+status.completed_today.map(id=>devices.find(d=>d.id===id)?.name||'機器').join('・')+'（0時にリセット／手動は制限なし）';}catch{$('listen-status').textContent='待ち受け状態を取得できません';}}const jobs=await api('/api/jobs');$('jobs').replaceChildren();if(!jobs.length)$('jobs').append(element('p','まだ同期・操作履歴はありません'));jobs.forEach(j=>{const row=element('div',undefined,'job '+j.state);row.append(element('strong',({queued:'待機中',running:'実行中',done:'完了',failed:'失敗',skipped:'スキップ'})[j.state]),element('span',`${({scan:'スキャン',pair:'ペアリング',sync:'同期'})[j.action]} — ${devices.find(d=>d.id===j.device_id)?.name||'Bluetooth'}`),element('small',`${dateText(j.created_at)}　${j.message}`));if(j.result){try{const detail=JSON.parse(j.result).diagnostic;if(detail){if(j.state==='failed'&&detail.stage==='discovery')row.append(element('p','未検出：機器との接続・データ読取りはまだ始まっていません。HBF-228Tは本体のBluetoothボタンを短く触れてから同期してください。NASとの距離やスマホとの同時接続も確認してください。','notice'));const box=element('details');box.append(element('summary','詳細診断・機器応答: '+(detail.stage||'不明')));if(detail.responses?.length)box.append(element('p',`機器応答 ${detail.responses.length}件（直近8件まで）。raw_hexには測定データが含まれる場合があります。共有する前に内容を確認してください。`));box.append(element('pre',JSON.stringify(detail,null,2)));row.append(box);}}catch{}}$('jobs').append(row);});const scan=jobs.find(j=>j.action==='scan');const scanKey=(scan?.id||'')+':'+(scan?.state||'')+':'+devices.map(d=>d.address).join(',');if(scanKey!==previousScanRender){renderScan(scan);previousScanRender=scanKey;}const state=jobs.map(j=>j.id+':'+j.state).join();if(previousJobState&&state!==previousJobState&&jobs.some(j=>j.state==='done')){await refreshMeta();await refreshRecords();}previousJobState=state;}
async function refreshDiagnostics(){
 const [d,s]=await Promise.all([api('/api/diagnostics'),api('/api/status')]);
 const rows={'バージョン':s.version,'CPU':s.architecture||'不明','USB Bluetooth':s.bluetooth_adapters.join(', ')||'未検出',
 'Bluetooth接続方式':d.expected_mode==='homehub'?'共通Bluetoothサービス':'直接接続（専用）',
 'Bluetooth実行環境':({homehub:'共通サービスに接続済み',container:'Container Station（専用）',native:'NASネイティブ',unavailable:'未接続'})[d.mode]||'未確認',
 '収集ワーカー':d.collection_paused?'データ保護のため停止':d.worker_alive?'稼働中':'停止','保存先':d.data_path};
 if(d.mode==='native'){rows['Python BLE']=d.bleak?'導入済み':'未導入';rows['D-Bus']=d.dbus?'検出':'未検出';}
 if(d.socket_path)rows['接続先']=d.socket_path;
 if(d.bridge_error)rows['ブリッジエラー']=d.bridge_error;if(d.watch_error)rows['自動同期エラー']=d.watch_error;if(d.bluezError)rows['Bluetooth復帰エラー']=d.bluezError;
 $('diagnostics').replaceChildren();Object.entries(rows).forEach(([k,v])=>$('diagnostics').append(element('dt',k),element('dd',v)));
 $('diagnostics-time').textContent=d.checked_at?'検査日時: '+dateText(d.checked_at*1000):'';
 $('diagnostic-checks').replaceChildren();
 for(const c of d.checks||[]){const row=element('div',undefined,'diagnostic '+c.level);row.append(element('strong',({ok:'正常',warning:'要確認',error:'要対応'})[c.level]+' · '+c.label),element('p',c.message));$('diagnostic-checks').append(row);}
 for(const guidance of d.guidance||[])$('diagnostic-checks').append(element('p',guidance,'notice'));
}
$('refresh-diagnostics').addEventListener('click',guarded(refreshDiagnostics));
$('import-form').addEventListener('submit',guarded(async()=>{const f=$('import-form'),file=f.elements.file.files[0];if(file.size>8*1024*1024)throw Error('CSVは8MB以内です');const result=await api('/api/import',{csv:await file.text(),user_id:f.elements.user_id.value||null});message(`${result.inserted}件取り込みました（重複${result.duplicates}件）`);await refreshRecords();}));
let omronPreview=null;
function clearOmronPreview(){omronPreview=null;$('omron-preview').replaceChildren();$('omron-apply').disabled=true;}
async function readOmronFile(file){
 const bytes=await file.arrayBuffer();
 try{return new TextDecoder('utf-8',{fatal:true}).decode(bytes);}
 catch{return new TextDecoder('shift_jis',{fatal:true}).decode(bytes);}
}
$('omron-file').addEventListener('change',clearOmronPreview);
$('omron-user').addEventListener('change',clearOmronPreview);
$('omron-history-form').addEventListener('submit',guarded(async()=>{
 const file=$('omron-file').files[0],userId=$('omron-user').value;
 if(!file||!userId)throw Error('CSVと取込先の利用者を指定してください');
 if(file.size>8*1024*1024)throw Error('CSVは8MB以内です');
 clearOmronPreview();const csv=await readOmronFile(file);
 const result=await api('/api/omron-history/preview',{csv,user_id:userId});
 omronPreview={csv,user_id:userId,preview_token:result.preview_token,importable:result.importable};
 $('omron-preview').append(element('p',`${result.model}・${result.total}件中、追加予定${result.importable}件・重複${result.duplicates}件。期間: ${dateText(result.first)} 〜 ${dateText(result.last)}。取込先: ${currentUserName(userId)}`));
 $('omron-apply').disabled=result.importable===0;
}));
$('omron-apply').addEventListener('click',guarded(async()=>{
 if(!omronPreview||omronPreview.user_id!==$('omron-user').value)throw Error('内容の確認をやり直してください');
 if(!confirm(`${currentUserName(omronPreview.user_id)}に${omronPreview.importable}件の履歴を追加しますか？`))return;
 const {csv,user_id,preview_token}=omronPreview;
 const result=await api('/api/omron-history/apply',{csv,user_id,preview_token});
 clearOmronPreview();$('current-user').value=$('omron-user').value;
 await refreshRecords();message(`${result.importable}件の過去データを反映しました（重複${result.duplicates}件）`);
}));
$('restore-form').addEventListener('submit',guarded(async()=>{const file=$('restore-form').elements.file.files[0];if(file.size>32*1024*1024)throw Error('バックアップは32MB以内です');if(!confirm('空の保存先にバックアップを復元します。続けますか？'))return;const result=await api('/api/restore',JSON.parse(await file.text()));await refreshMeta();await refreshRecords();message(`${result.restored}件復元しました。Bluetoothは再ペアリングしてください`);}));
$('apply-filter').addEventListener('click',guarded(async()=>{if($('since').value&&$('until').value&&$('since').value>$('until').value)throw Error('開始日を終了日以前にしてください');offset=0;await refreshRecords();}));
$('current-user').addEventListener('change',guarded(async()=>{offset=0;resetRecord();await refreshRecords();}));$('history-kind').addEventListener('change',guarded(async()=>{offset=0;await refreshHistory();}));$('chart-metric').addEventListener('change',renderCharts);$('previous').addEventListener('click',guarded(async()=>{offset=Math.max(0,offset-100);await refreshHistory();}));$('next').addEventListener('click',guarded(async()=>{offset+=100;await refreshHistory();}));
(async()=>{try{await refreshMeta();resetRecord();await refreshRecords();await refreshJobs();if(!users.length){showPage('settings');message('最初に利用者を追加してください。その後、手入力や機器の登録ができます。');}setInterval(()=>{if(!document.hidden){markMeasuredToday('bp-today-star',chartRecords.find(r=>r.kind==='blood_pressure'));markMeasuredToday('weight-today-star',chartRecords.find(r=>r.kind==='body_composition'));refreshJobs().catch(()=>{});}},5000);}catch(error){showPage('settings');message('読み込みに失敗しました: '+error.message,true);}})();
